/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ReliefGNM3.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ReliefGNM3.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[2.4, -0.05, -0.05]}>
        <mesh geometry={nodes.Model_1.geometry} material={materials.material0} />
        <mesh geometry={nodes.Model_2.geometry} material={materials.HoverTuch} />
        <mesh geometry={nodes.Model_3.geometry} material={materials.HoverJesus} />
        <mesh geometry={nodes.Model_4.geometry} material={materials.HoverVeronika} />
        <mesh geometry={nodes.Model_5.geometry} material={materials.HoverLeft} />
        <mesh geometry={nodes.Model_6.geometry} material={materials.HoverMiddle} />
        <mesh geometry={nodes.Model_7.geometry} material={materials.HoverRightBack} />
        <mesh geometry={nodes.Model_8.geometry} material={materials.HoverRightFront} />
        <mesh geometry={nodes.Model_9.geometry} material={materials.HoverBroken} />
        <mesh geometry={nodes.Model_10.geometry} material={materials.HoverSchwertreste} />
      </group>
    </group>
  )
}

useGLTF.preload('/ReliefGNM3.glb')
